### ISSUE TITLE
no source distribution on pypi

### ISSUE THREAD

**Issue by Anthchirp** [alexmojaki/executing#15]
Would it be possible to upload the `sdist` in addition to the wheel file on pypi? Currently the conda-forge distribution does not automatically pick up updates unless the sources are present.

**Comment by alexmojaki** [comment]
@KOLANICH you championed the change in relase process, how would I best do this?

**Comment by Anthchirp** [comment]
looking at your release.sh it could be as simple as replacing

```bash
python3 -m pep517.build -b .
twine upload ./dist/*.whl
```

with

```bash
python3 -m pep517.build -bs .
twine upload ./dist/*
```

although -as of now- I'm not familiar with pep517 (yet)

**Comment by KOLANICH** [comment]
@alexmojaki, the fix proposed by @Anthchirp LGTM. The only improvement is IMHO just restricting file extensions of the stuff being uploaded. Who knows what else can go to `dist` dir in future, so we don't want the process to fail because of pypi rejecting to accept some files, or even worse, upload anything that doesn't belong to pypi.

**Comment by Anthchirp** [comment]
since you delete and create the directory in the step directly before that you should only get legitimate build artifacts in there. If that then fails - you'd want to know about it :slightly_smiling_face:

But you are right, `twine upload dist/*.whl dist/*.tar.gz` is a distinct improvement as it ensures that you get files for both extensions.

**Comment by alexmojaki** [comment]
Fixed in https://github.com/alexmojaki/executing/commit/8cb2c349fd5aa29db5a5a3c63d880c8339d198ff

Thanks for your help! Both kinds are now available at https://pypi.org/project/executing/0.5.3/#files

**Comment by KOLANICH** [comment]
BTW, pep517 tool is deprecated in favour of https://github.com/pypa/build
