### ISSUE TITLE
Support pytest

### ISSUE THREAD

**Issue by alexmojaki** [alexmojaki/executing#2]
pytest modifies the AST under the hood to show informative error messages when a plain `assert` fails. This affects the bytecode in ways `executing` doesn't expect. I'm not actually sure if it's possible to robustly deal with this, but it's worth taking a look at.

**Comment by alexmojaki** [comment]
Done in #3, at least for nodes outside of assert statements. Inside assert statements, the bytecode is modified too much and I don't think it's feasible.

**Comment by 15r10nk** [comment]
I hope that [this](https://github.com/pytest-dev/pytest/issues/12818) pull-request can solve the problem with nodes inside assert statements (at least for python>=3.11).
