### ISSUE TITLE
Executing cannot find node inside Jupyter lab/notebooks

### ISSUE THREAD

**Issue by aroberge** [alexmojaki/executing#23]
Using friendly, I found that excuting could not locate the correct location of a node causing a problem inside Jupyter notebooks (or Jupyter lab) but could do so with IPython.  First, here's a screen capture showing the correct result using IPython, with some additional outputs from print statements inserted for this specific report.

![image](https://user-images.githubusercontent.com/629698/126869262-f8b7953a-f72b-4990-b5ea-f5cd3aa77796.png)

Next, the same code run within a Jupyter notebook
![image](https://user-images.githubusercontent.com/629698/126869274-f2c3e356-5eb0-4064-8820-6ee25f9ffca1.png)

Perhaps this is is caused by the new way that Jupyter runs code, using temporary files instead of using exec() on code.

With the "old" friendly-traceback (before it made use of stack_data), when Jupyter was not using temporary files, I see from screen captures on https://aroberge.github.io/friendly-traceback-docs/docs/html/jupyter.html that the location was correctly picked up.

**Comment by alexmojaki** [comment]
IPython needs special treatment, and executing uses the `<ipython-input-*>` filename pattern to determine if it's in IPython. See https://github.com/alexmojaki/executing/blob/master/executing/executing.py#L295-L296

The switch to files is annoying, I'll need to find a new way to reliably detect an IPython code object. This also affects snoop: https://github.com/alexmojaki/snoop/blob/49ce617297fcdd5efa46de70626a64997eee724d/snoop/tracer.py#L45

Thanks for letting me know about this.

**Comment by aroberge** [comment]
So far, it seems that all files have names that contain `ipykernel_`.  This is assigned in https://github.com/ipython/ipykernel/blob/7ed57cb4a03e719074c373029cf9f2e6dfd2c6de/ipykernel/compiler.py#L39

Future versions may include the code cell as information according to https://github.com/ipython/ipython/pull/13043

**Comment by aroberge** [comment]
The following code:
```python
                            if (
                                code.co_filename.startswith("<ipython-input-")
                                or "Temp/ipykernel_" in code.co_filename
                            ) and code.co_name == "<module>":
```
seems to fix the problem.

![image](https://user-images.githubusercontent.com/629698/127557086-94107b88-773b-450f-b45a-c78bae3960be.png)

**Comment by alexmojaki** [comment]
Released 0.8.0, please upgrade and confirm that this is fixed for you and that Python 3.10 also works.

**Comment by aroberge** [comment]
Everything that I tested is working.

I only have automated tests for friendly-traceback (and not the friendly UI layer).  Requiring friendly-traceback to use executing 0.8.0 did not change anything (as expected since it does not involve ipython): all tests pass, with Python 3.6 to 3.10 inclusively.  

I normally only test ipython/jupyter with Python 3.9.  

Doing a single test similar to the one above `b = 4 + math.Pi`:

- iPython 7.25.0 (which uses the `<ipython-...`: works correctly (`math.Pi` identified as problematic node)
- Jupyter lab (which uses temporary files): works correctly
- Jupyter notebook (same as lab): works correctly.

With Python 3.10.0b4

- ipython works correctly
- jupyter notebook: works correctly
- jupyter lab:  seems to be stuck during installation; not tested.  If I manage to get it install, I'll report the test result.
```
INFO: This is taking longer than usual. You might need to provide the dependency resolver
with stricter constraints to reduce runtime.
If you want to abort this run, you can press Ctrl + C to do so. ....
```

**Comment by alexmojaki** [comment]
Excellent! Thanks for your help.
