### ISSUE TITLE
NameError: f-string node cannot be identified

### ISSUE THREAD

**Issue by aroberge** [alexmojaki/executing#24]
Here's an example I found:
```
> python -m friendly_traceback

Friendly-traceback version 0.4.28. [Python version: 3.8.10]
Type 'Friendly' for help on special functions/methods.

[1]: print(f"Here is {xxx} again")

Traceback (most recent call last):
  Code block [1], line 1, in <module>
    print(f"Here is {xxx} again")
NameError: name 'xxx' is not defined

[2]: tb = Friendly._get_tb_data()

[3]: print(tb.node)
None
```
I would not be surprised if it would be impossible to extract the relevant information, due to the way that fstrings are evaluated. Still, just in case, I thought it was worth reporting.

What prompted me to try this example is a bug report on Python https://bugs.python.org/issue44885 for the planned 3.11 version which will include more information about the exact location of an error.

Feel free to close this issue as being "out of scope".

**Comment by alexmojaki** [comment]
This is actually the oldest open issue on asttokens: https://github.com/gristlabs/asttokens/issues/6

I don't see this being solved without changes to Python.

Btw, I'm hoping that in 3.11 I'll be able to use the new information as a better implementation of this library, essentially making the tricks here obsolete.
