### ISSUE TITLE
Let GH index who's using this package

### ISSUE THREAD

**Issue by pwwang** [alexmojaki/executing#25]
After experimenting a little bit, I found that for python packages, including a `requirements.txt` in the repo would enable GH to index who's using the package. 

The list can be seen on both the main page of the repo or `Insights` -> `Dependency graph` -> `Dependents`

**Comment by pwwang** [comment]
Looks like I am wrong. I find another case without a `requirement.txt` file but GH tracks the dependents:

https://github.com/has2k1/plotnine

Looks like it's something inside `setup.py`. Will keep looking.

**Comment by aroberge** [comment]
Almost two years ago, I noticed that Github showed an incorrect "used by" count for a new project I had created, and that no one else was using. Here is part of an email I wrote:
![image](https://user-images.githubusercontent.com/629698/131245594-8cabc7ab-1492-4097-be95-17062c04a083.png)

That was eventually corrected...

Today, looking at its network dependency page, it **apparently** has 14 dependents.  https://github.com/aroberge/ideas/network/dependents
Looking more closely, one of them (https://github.com/faclib/ezcomponents) has a single commit done 7 years ago, 5 years before ideas was created.

I have no idea how github does its count ... but I don't think it can be relied upon!

**Comment by alexmojaki** [comment]
That's a much more subtle issue to get right. On the other hand, you'd think that all these projects which list executing as a dependency:

- https://github.com/pwwang/python-varname/network/dependencies
- https://github.com/friendly-traceback/friendly-traceback/network/dependencies
- https://github.com/alexmojaki/futurecoder/network/dependencies

would be listed in executing as a dependent. Why can't they use their own graph correctly?

I'm going to delete requirements.txt, I don't want it misleading people.

**Comment by pwwang** [comment]
There is a discussion here:

https://github.community/t/bug-project-not-showing-network-dependents/3161/53

Looks like `setup.py` is where the dependents are parsed. [One comment](https://github.community/t/bug-project-not-showing-network-dependents/3161/54) mentioned that the package name inside `setup.py` may matter.

I'll try it on `python-varname` and let you know.

**Comment by pwwang** [comment]
@aroberge @alexmojaki 

Wow!

I just moved the `name` into the `setup` function in `setup.py` and the dependents populated immediately!

See commit: https://github.com/pwwang/python-varname/commit/017c1f24952281aada86705d4c419e4677c58a29

**Comment by alexmojaki** [comment]
But it's still dumb that they're doing the parsing on both sides...

**Comment by pwwang** [comment]
> But it's still dumb that they're doing the parsing on both sides...

Agreed. Mind a PR from me to update `setup.py`?

**Comment by aroberge** [comment]
I just did this for friendly-traceback and found out that there are a dozen of dependents.

**Comment by pwwang** [comment]
> I just did this for friendly-traceback and found out that there are a dozen of dependents.

Cheers!

**Comment by alexmojaki** [comment]
Well that worked, now it shows a huge number of dependents. It's not that exciting though, seems to mostly be people using `icecream` (which already shouldn't be an actual dependency) who have pinned all their recursive dependencies.

**Comment by aroberge** [comment]
Perhaps you are after this number: https://github.com/alexmojaki/executing/network/dependents?dependent_type=PACKAGE

**Comment by pwwang** [comment]
> Well that worked, now it shows a huge number of dependents. It's not that exciting though, seems to mostly be people using `icecream` (which already shouldn't be an actual dependency) who have pinned all their recursive dependencies.

Yes, but you can't blacklist them...

**Comment by alexmojaki** [comment]
> Perhaps you are after this number: https://github.com/alexmojaki/executing/network/dependents?dependent_type=PACKAGE

Half of these don't mention `executing` at all, seems like GH being drunk again.

> Yes, but you can't blacklist them...

I mean I'm glad people are using icecream but I want to know who's using executing directly for cool metaprogramming and actual features in the project, not fancy print debugging.
