### ISSUE TITLE
Support for Python 3.11?

### ISSUE THREAD

**Issue by aroberge** [alexmojaki/executing#30]
With today's release of Python 3.11.0a3, I suddenly have many failing tests for friendly-traceback that were still passing with 3.11.0a2.  It looks like the nodes are no longer properly identified.

For example, if I have 
```
a = (1, 2)(3, 4)
```
the node was previously identified as `(1, 2)(3, 4)` whereas now it is the entire line that is identified as the problematic node.

I can provide more examples if needed, but I suspect that your own unit tests would likely give you some results.  It might be that the problem is upstream (with asttoken) instead of in executing.

**Comment by aroberge** [comment]
The newest version of executing (0.9.1) is breaking one of my tests ... in a good way!

I'm about to start adding back some tests that were skipped for Python 3.11 as executing was not able to identify some nodes as it did in older previous versions.  I thought that I should start by checking that nothing was broken when using older Python versions. I found out that one of my tests was broken.
Previously, using Python 3.6--3.10, for
```
a = list(range(10))
b = []
c, b[1] = 1, 2
```
executing was not able to identify the object causing the problem and leading to the following explanation from friendly_traceback:
```
You have tried to assign a value to an item of an object
of type `list` which I cannot identify.
```

My test was seeing if that message was present ... and it is not since executing now **can**
identify the problematic object:

```
You have tried to assign a value to index `1` of `b`,
a `list` which contains no item.
```

Obviously, this is the opposite of an issue needing to be fixed in executing, but I thought I should document it as it is something positive coming out of the changes done to make executing work with Python 3.11. Thanks to all involved.

I will report back here if I find any failing tests in my suite using Python 3.11 -- or not.

**Comment by alexmojaki** [comment]
Great! This is actually the result of https://github.com/alexmojaki/executing/pull/38 which was initiated by @pwwang. None of the 3.11 code has been released.

**Comment by aroberge** [comment]
Ah ... I thought the just-released version 0.9.1 contained the changes for 3.11. I'm relieved that it does not since I had just found out that it was not working properly. I am eagerly awaiting a release supporting 3.11!

**Comment by frenzymadness** [comment]
I'm a little bit confused as well. Why did you release a major stable version 1.0.0 without support for Python 3.11?

**Comment by alexmojaki** [comment]
Because I released some changes related to cache invalidation, which could theoretically be breaking changes for some people. executing needed to graduate away from 0.x at some point, it seemed like a good time.

**Comment by frenzymadness** [comment]
Okay, makes sense, thanks for the explanation.

**Comment by alexmojaki** [comment]
Released Python 3.11 support in executing version 1.1.0 !!!

Big thanks again to @15r10nk 

cc @samuelcolvin @gruns @hrnciar

**Comment by samuelcolvin** [comment]
thanks so much.

**Comment by paulwouters** [comment]
awesome!
