### ISSUE TITLE
Is it possible to know whether a frame is from a method call?

### ISSUE THREAD

**Issue by laike9m** [alexmojaki/executing#4]
For example
```python
def do_func(self):
    frame = sys._getframe()

class A:
    def do_method(self):
        frame = sys._getframe()
```

Is it possible to know whether frame is inside a regular function call or method call? From https://stackoverflow.com/q/2203424/2142577 it seems this is no way except relying on the convention that `self` is the first argument of method signature. Do we have a better way?

I also tried using `gc.get_referrers(frame.f_code))`, but it turns out the code is referrenced by the unbound function, no matter whether it is actually a method.

**Comment by alexmojaki** [comment]
Sure, look at the code which calculates the `qualname` of a code object. Maybe instead of storing just a string, it could store a list of AST nodes. Then you could check if that list contains a ClassDef.

**Comment by laike9m** [comment]
Right, looks like it's possible. Do you want to add this feature?

**Comment by alexmojaki** [comment]
Actually there's a simpler way. Get a statement with `list(executing_object.statements)[0]` then iterate through the `.parent`s. If there's a `FunctionDef` and a `ClassDef` it's a method. It should work for everything except for methods defined by lambdas, e.g.

```python
class A:
    foo = lambda self: 0
```

**Comment by laike9m** [comment]
Great, this works pretty well. I'm ignoring the lamda case since it's so rare. Thanks for help.
