### ISSUE TITLE
Automated tests for IPython

### ISSUE THREAD

**Issue by alexmojaki** [alexmojaki/executing#59]

**Comment by 15r10nk** [comment]
hi, I started the work on #42 and need some refactoring on the NodeFinder API
(make the NodeFinder to an attribute of Source and extract the Source._nodes_by_line stuff into NodeFinder, because this differs for each implementation ... but this is not the point of my question ).

I have to touch the ipython code if I want to refactor anything there.
So I think it is the best to work on this issue first.

Have you already an idea how to test the ipython code?
Does it only has to run with `ipython some_script.py` or also in some cell in the web form.

**Comment by alexmojaki** [comment]
> Does it only has to run with `ipython some_script.py` or also in some cell in the web form.

You shouldn't have to use the web form (jupyter) as IPython has a CLI. But running `ipython some_script.py` doesn't work as a test because it doesn't trigger the IPython magic that needs to be accounted for where each statement runs in a separate code object. Here's a demo:

```
$ ipython
Python 3.11.0 (main, Oct 27 2022, 23:16:13) [GCC 7.5.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import inspect  # press ctrl+o for multiline cell in the terminal
   ...: import dis
   ...: dis.dis(inspect.currentframe().f_code)  # only this statement gets disassembled below
  0           0 RESUME                   0

  3           2 LOAD_NAME                0 (dis)
              4 LOAD_METHOD              0 (dis)
             26 LOAD_NAME                1 (inspect)
             28 LOAD_METHOD              2 (currentframe)
             50 PRECALL                  0
             54 CALL                     0
             64 LOAD_ATTR                3 (f_code)
             74 PRECALL                  1
             78 CALL                     1
             88 PRINT_EXPR
             90 LOAD_CONST               0 (None)
             92 RETURN_VALUE

In [2]:                                                                                                                                                                                                     
Do you really want to exit ([y]/n)? 
$ ipython some_script.py  # same contents as the cell above, now you see all the instructions
  0           0 RESUME                   0

  1           2 LOAD_CONST               0 (0)
              4 LOAD_CONST               1 (None)
              6 IMPORT_NAME              0 (inspect)
              8 STORE_NAME               0 (inspect)

  2          10 LOAD_CONST               0 (0)
             12 LOAD_CONST               1 (None)
             14 IMPORT_NAME              1 (dis)
             16 STORE_NAME               1 (dis)

  3          18 PUSH_NULL
             20 LOAD_NAME                1 (dis)
             22 LOAD_ATTR                1 (dis)
             32 PUSH_NULL
             34 LOAD_NAME                0 (inspect)
             36 LOAD_ATTR                2 (currentframe)
             46 PRECALL                  0
             50 CALL                     0
             60 LOAD_ATTR                3 (f_code)
             70 PRECALL                  1
             74 CALL                     1
             84 POP_TOP
             86 LOAD_CONST               1 (None)
```

Unfortunately I tried looking at the IPython tests and couldn't understand how to write a simple test outside the IPython repo that just runs one multiline cell and checks the output. Maybe @Carreau can advise. Or maybe the solution is just to run the ipython shell and pipe some code into its stdin. I just noticed you don't have to actually press ctrl+o and enter multiple lines, you can get the same effect by separating statements with semicolons.
