### ISSUE TITLE
Misuse of list in _position_node_finder.get_instructions

### ISSUE THREAD

**Issue by DManowitz** [alexmojaki/executing#65]
The return type of this function is given as `list[dis.Instruction]`, but it should be `List[dis.Instruction]`, with `List` imported from `typing`.  This causes a TypeError (at least with Python 3.7 and 3.8) when trying to import.

**Comment by alexmojaki** [comment]
`_position_node_finder` is specifically for Python 3.11 only, in what context is it being imported?

**Comment by DManowitz** [comment]
Sorry.  That must have gotten imported by mistake.
