### ISSUE TITLE
tests are failing for storing to two attributes with the same name

### ISSUE THREAD

**Issue by 15r10nk** [alexmojaki/executing#68]
I'm currently working on #64 and have some problems with the tests for 3.7 (reproducible on master)

The pipeline which is failing is the following:
https://github.com/alexmojaki/executing/actions/runs/4362346591/jobs/7627135034

I minimized the problem down to the following line (file was stored in tests/small_samples):

``` python
__arg.__deprecated__ = __new__.__deprecated__ = __msg
```

part of the test output (python 3.7.15):
```
mapping failed
Expected one value, found 2
search bytecode Instruction(opname='STORE_ATTR', opcode=95, arg=2, argval='__deprecated__', argrepr='__deprecated__', offset=6, starts_line=None, is_jump_target=False)
```

I don't know if this issue could be fixed in the SentinelNodeFinder or if it should be handled as an known issue and be ignored.

I also don't know why it started to appear now.

**Comment by alexmojaki** [comment]
It's a known issue that should be ignored.

https://github.com/alexmojaki/executing/blob/0e5096a4506e2f0d84fe306516fbb89003eaa8a8/tests/test_main.py#L837-L841

**Comment by 15r10nk** [comment]
Interesting. I will try to figure out why it is not. Thank you.

**Comment by 15r10nk** [comment]
the error is already handled here and raised in the last line.

https://github.com/alexmojaki/executing/blob/0e5096a4506e2f0d84fe306516fbb89003eaa8a8/tests/test_main.py#L1246-L1303

The code that you mentioned is never executed in this case.

**Comment by 15r10nk** [comment]
I think the problem are the open issues in the SentinelNodeFinder.

https://github.com/alexmojaki/executing/blob/0e5096a4506e2f0d84fe306516fbb89003eaa8a8/tests/test_main.py#L679-L685

This issue here is just one more. I skipped `test_module_files` in #64 for python < 3.8 for now.

This issues should be fixed later or categorized as KnownIssues.

But don't know if I will have time for this.
