### ISSUE TITLE
Release missing for 0.4.3

### ISSUE THREAD

**Issue by inakimalerba** [alexmojaki/executing#7]
Dear Maintainer,

The package version number was bumped on https://github.com/alexmojaki/executing/commit/943ad1afdcea27ffbe13c580802c1376672e16db but no release was tagged on GitHub.

Could you please create it?

Thanks !

**Comment by alexmojaki** [comment]
Done.

I had released on PyPI. Can you explain why GitHub releases are significant to you? I don't use them myself.

**Comment by inakimalerba** [comment]
I'm maintaining the package for Debian, and we get the source from Github not pypi.

The tool we use to package keeps track of the sources pointed on [this](https://salsa.debian.org/debian/python-icecream/-/blob/master/debian/watch) file.

**Comment by inakimalerba** [comment]
Thanks for fixing the problem btw :)
