### ISSUE TITLE
3.13 build is surprisingly slow

### ISSUE THREAD

**Issue by alexmojaki** [alexmojaki/executing#87]
Before 3.11, tests are expected to take long, mostly for `test_sys_modules`. But for 3.11+, the new node finder should be consistently fast.

In https://github.com/alexmojaki/executing/actions/runs/10548894285/job/29223305836:

- 3.11 took 1m47s
- 3.12-dev took 3m23s
- 3.13-dev took 21m33s

These are times reported by pytest, so they shouldn't include installing dependencies or anything.

**Comment by 15r10nk** [comment]
I will look into it.

**Comment by 15r10nk** [comment]
It looks like the deadcode detection is the problem (maybe the deepcopy).

```
         108501261 function calls (91608472 primitive calls) in 143.263 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    155/1    0.026    0.000  143.482  143.482 {built-in method builtins.exec}
        1    0.000    0.000  143.482  143.482 codi.py:1(<module>)
        1    0.008    0.008  143.239  143.239 codi.py:12(test_file)
        1    0.053    0.053  143.211  143.211 test_main.py:836(check_filename)
      167    0.451    0.003  140.715    0.843 deadcode.py:77(is_deadcode)
11531183/167   39.415    0.000   96.382    0.577 copy.py:119(deepcopy)
608047/167   12.873    0.000   96.378    0.577 copy.py:248(_reconstruct)
608047/167   15.357    0.000   96.372    0.577 copy.py:218(_deepcopy_dict)
322143/334    1.340    0.000   96.366    0.289 copy.py:192(_deepcopy_list)
```

The good news is that the deadcode detection is only part of the tests.
But I will look into it and try to find the reason.

One option might be to use the deadcode detection from the index_node_finder branch (this is the original implementation without deepcopy).

**Comment by 15r10nk** [comment]
The deepcopy of one module (`bird.py`) went from 0.184 to 0.441.
The other part of the explanation is that is_deadcode was called:

* 3 times for python 3.12
* and 167 times for 3.13

during the analysis of `bird.py`.
I will investigate this difference in the call count later.
It looks suspicious.

**Comment by 15r10nk** [comment]
I moved the is_deadcode check to the end which reduced the amount of checks which are performed.
The reason why deepcopy of an ast is slower now is probably that the implementation has changed https://github.com/python/cpython/issues/120108.
